### ISSUE TITLE
Latest ver crashes on Linux

### ISSUE THREAD

**Issue by 19s-fautley-k** [Zergatul/cheatutils#1]

**Comment by Zergatul** [comment]
I don't think issue can be linux related. Forge guys changed APIs somewhere in the middle of 1.19 releases. And all mods compiled for old forge versions will crash. Latest 1.19 version works with Forge 41.0.16, and crash with 41.0.99. Somewhere in between they changes APIs. I will need to make few changes in order to make it works in newer versions.

**Comment by 19s-fautley-k** [comment]
OK, thanks, I will use 41.0.16, wish you luck in fixing the problem

**Comment by Zergatul** [comment]
I just released new version, it should work with latest Forge.
