### ISSUE TITLE
Free cam on 1.18.2 doesn't work

### ISSUE THREAD

**Issue by SHADOW-WOLF-FURRY** [Zergatul/cheatutils#16]
attempting to use free cam on the 1.18.2 latest version causes the camera to go into an f5 like view and locks it to that position, you are still able to move a sort of ghost camera entity around ad interact with nearby blocks but your view doesnt move with the camera entity

**Comment by Zergatul** [comment]
do you have better 3rd person mod? or other similar mods

**Comment by SHADOW-WOLF-FURRY** [comment]
dont think so, im playing the Encrypted_ modpack and as far as im aware it doesnt contain any similar mods

**Comment by Zergatul** [comment]
some random mod may change distance to camera in 3rd person and if they are not doing it correctly it can break my free cam.
I remember when developers of Create mod added this, and I developed fix in 2 mods.
Your problem is definitely looks like conflict. Many players use 1.18.2 cheatutils version and everyone use freecam.

It is hard to fix these compatibility issues. First we need to find which mod creates conflict. Then I need to check source code of conflicting mod (assuming it is open source, and not all mods are). Then I need to reach developers of this mod, propose change and explain why we need it.

**Comment by SHADOW-WOLF-FURRY** [comment]
yeah, create and most of its addons are installed. oh well, thanks for quick feedback on it but i dont really need enough to go searching for anything on it
