### ISSUE TITLE
Fabric version not working (1.19.2)

### ISSUE THREAD

**Issue by githubUser947** [Zergatul/cheatutils#3]
i downloaded the fabric version and loaded minecraft but it didnt show up in modmenu.

i checked the file and saw no fabric.mod file in it

if the 'fabric version' wasn't actually fabric, please either delete it or fix it.

Thank you

**Comment by Zergatul** [comment]
Sorry, I marked file as fabric by mistake

**Comment by githubUser947** [comment]
In the future, is it possible to have a fabric port. I understand it is hard maintaining two modloaders at once and I will totally respect your opinion and choice.

sorry for disturbing you with such a annoying question. I am sorry.

**Comment by Zergatul** [comment]
Asking questions is fine.
I have smaller mod published on curseforge - freecam, and I support here fabric and forge, and different MC versions starting from 1.16.5. This mod has about 2% functionality (and amount of code) of cheatutils mod, and it is quite annoying to make changes here. You need to have all MC versions installed (with 2 mod loaders), you need to have all devkits installed, test changes in dev environment and in real environment. Making simple fix for all versions can take 1-2 hours. Even if I could say I love coding, but this time is spent on some annoying things like copying jar files, launching different MC version and test if changes work here.
Imagine supporting 2 mod loaders and different versions of cheatutils. This will be headache for me. I already stopped adding new changes to 1.18.2 version.
I totally understand your question, because about year ago I knew nothing about modding and I was sad when seeing some good mod is not supported for forge.

**Comment by Zergatul** [comment]
I will try to port some modules as fabric version of the mod on weekend. This should be as hard as creating new mod. You are interesting on blocks/entities esp and hotkeys?

**Comment by githubUser947** [comment]
Thank you for both the quick response and for the port. Yes, I am mainly interested in entity esp and hotkeys.

**Comment by githubUser947** [comment]
Though block esp is also a nice feature.

**Comment by Zergatul** [comment]
Just finished dev version, everything was working fine. Created release jar. Tried it, and see this. I hate fabric...
![fabric-entities](https://user-images.githubusercontent.com/1272144/187029761-a651a030-b252-4b3c-a307-8ac59bfb4006.png)

**Comment by githubUser947** [comment]
Thank you! I appreciate your work!
Thank you once again!

**Comment by githubUser947** [comment]
Please do send the link or the mod file!

**Comment by Zergatul** [comment]
I have problems with Entity ESP. Fabric reobfuscates entity class names into "class_1234". In Forge you would see real class names like "Monster", "Zombie", "Item" and so on, but when I build fabric release jar, all these names change to "class_0123".

**Comment by Zergatul** [comment]
Uploaded new version on curseforge

**Comment by githubUser947** [comment]
How does scripting of esp work?
i tried according to the forge tutorial but it didnt toggle

**Comment by Zergatul** [comment]
Entities don't work from scripting (due to problem with classes I was angry about). Blocks are working fine. I will fix entities.

**Comment by githubUser947** [comment]
Ok thanks!

**Comment by Zergatul** [comment]
I uploaded 0.8.1 version for fabric with fix
