### ISSUE TITLE
every esp not working

### ISSUE THREAD

**Issue by brickyosu** [Zergatul/cheatutils#45]
i do not know why, but when i try to use esp on cheatutils, it does not do anything

here are my mods:
baritone
boosted brightness
continuity
essential client
indium
iris
mod menu
sodium
trajectory preview

**Comment by brickyosu** [comment]
also, can you make it so when im using baritone, i can use freecam without freecam moving?

**Comment by Zergatul** [comment]
Investigating mods compatibility issues is not fun for me. You need to pinpoint exact mod causing problems, and then I may look into the problem (assuming another mod is open source), but with no promises.
I have no idea what most of your mods do, but drawing ESP lines doesn't work with optifine shaders. If you are using something like that it can be a problem. Also you may accidentally turn ESP off with default hotkey.
Baritone may be exception, since it is very popular.

**Comment by brickyosu** [comment]
ohhhh, my hotkey was why my esp didnt work. im so stupid 😭😭😭😭

**Comment by brickyosu** [comment]
my block esp doesnt work, but i'll just download a mod that will help me with that
